[build]
  publish = "."

[[redirects]]
  from = "/workspace"
  to = "/workspace/index.html"
  status = 200

[[redirects]]
  from = "/workspace/*"
  to = "/workspace/index.html"
  status = 200

[[headers]]
  for = "/workspace"
  [headers.values]
    Basic-Auth = "lina:FilinaPodcast2026"

[[headers]]
  for = "/workspace/*"
  [headers.values]
    Basic-Auth = "lina:FilinaPodcast2026"
